console.log("Sorry");
var firstName = "Abdur";
var lastName = "Rahim";
var fullName = firstName + " " + lastName;
console.log(fullName);
var applePrice = 44;
var orangePrice = 32;
var totalPrice = applePrice + orangePrice;
console.log(applePrice);
console.log(orangePrice);
console.log(totalPrice);
console.log(typeof totalPrice);
console.log(typeof fullName);
console.log(new Date);